version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: chefs
      POSTGRES_PASSWORD: chefs
      POSTGRES_DB: chefsquest
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
